services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: videoeditor-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    networks:
      - videoeditor-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: videoeditor-backend
    ports:
      - "8000:8000"
    volumes:
      - ./out:/app/out
    networks:
      - videoeditor-network
    # Memory configuration for video rendering
    mem_limit: 2g
    memswap_limit: 2g
    shm_size: 1g

networks:
  videoeditor-network:
    driver: bridge