# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: affil
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: network
# "service" is the name of this project. This will also be added to your AWS resource names.
service: video-renderer

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 900 # 15 minutes timeout for video rendering
  memorySize: 3008 # 3GB memory
  environment:
    NODE_OPTIONS: --max-old-space-size=2560
    REMOTION_LAMBDA_FUNCTION_NAME: ${env:REMOTION_LAMBDA_FUNCTION_NAME}
    REMOTION_S3_BUCKET_NAME: ${env:REMOTION_S3_BUCKET_NAME}
    REMOTION_SERVE_URL: ${env:REMOTION_SERVE_URL}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource: 
            - arn:aws:lambda:us-east-1:*:function:remotion-render-*
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::remotionlambda-*/*
            - arn:aws:s3:::remotionlambda-*

package:
  patterns:
    - '!**'
    - 'dist/**'
    - 'node_modules/**'

functions:
  api:
    handler: dist/remotion-handler.handler
    events:
      - httpApi: "*"